# Generated by Django 3.0.8 on 2021-02-06 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='N/A', max_length=200, null=True, verbose_name='Model vehicle')),
                ('color', models.CharField(max_length=200, verbose_name='Color vehicle')),
                ('mark', models.CharField(max_length=200, verbose_name='Mark of vehicle')),
                ('vehicle_assignment', models.BooleanField(default=False, verbose_name='vehicle assignment')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Update date')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicule_person', to='persona.Person')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='assignmentVehiclePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(verbose_name='Expiration date')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_person', to='persona.Person')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigment_vehicle', to='vehiculo.Vehicle')),
            ],
            options={
                'db_table': 'assignment_vehicle_person',
            },
        ),
    ]
