# Generated by Django 3.0.8 on 2021-02-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of person')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='Email contact')),
                ('phone_number', models.BigIntegerField(verbose_name='Number phone contact')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Update date')),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
